<?php

ini_set('session.use_only_cookies', 1);
ini_set('session.use_strict_mode', 1);

session_set_cookie_params([
   'lifetime' => 1800, // 30 minutes
   'domain' => 'localhost', // we only used cookies generated by localhost
   'path' => '/', // it'll work in any directory
   'secure' => true, // will only work on https connections
   'httponly' => true // restricts any script access from our client
]);

session_start();

// regenerating session ID every 30 minutes
if (!isset($_SESSION['last_regeneration'])) { // the first time starting a session

   session_regenerate_id(true); // will generate a new session ID, more secure
   $_SESSION['last_regeneration'] = time();
} else {
   
   $interval = 60 * 30;
   
   if (time() - $_SESSION['last_regeneration'] >= $interval) {
   
      session_regenerate_id(true);
      $_SESSION['last_regeneration'] = time();
   }
}